### ISSUE TITLE
这个文件引用错了，很全的一个工具，麻烦更新一下，非常感谢

### ISSUE THREAD

**Issue by whiteHus** [lanzhsh/react-vue-koa#4]
![image](https://user-images.githubusercontent.com/37429685/70201225-e9780180-1750-11ea-8fda-7d63cb9dbe59.png)

**Comment by lanzhsh** [comment]
才看到,npm 包已经更新了,你再重新 npm i 一下,谢谢提醒哒

**Comment by lanzhsh** [comment]
github 仓库代码也已经更新

**Comment by whiteHus** [comment]
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lanzhsh"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月9日(星期一) 上午9:14
收件人:&nbsp;"lanzhsh/react-vue-koa"<react-vue-koa@noreply.github.com&gt;;
抄送:&nbsp;"阙忠锦"<1145622341@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lanzhsh/react-vue-koa] 这个文件引用错了，很全的一个工具，麻烦更新一下，非常感谢 (#4)




才看到,npm 包已经更新了,你再重新 npm i 一下,谢谢提醒哒
